server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  messages:
    basename: i18n/Messages
  zipkin:
    enabled: true
    base-url: http://localhost:7777/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  rabbitmq: 
    host: 120.78.162.226
    port: 5672
    username: admin
    password: 123456
  datasource:
    username: root
    password: azz2025
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.162.226:3306/azz_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: false
    
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
azz: 
   datasource:
    dataSourceConfig: 
      -
        url : jdbc:mysql://120.78.162.226:3306/azz_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        db: azz_dev
        defaultDatasource: true
        username: root
        password: azz2025
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        maxOpenPreparedStatements: 20
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    monitorConfig:
      available: true
      allow: 127.0.0.1
      deny: 127.0.0.2
      loginUsername: admin
      loginPassword: 123456
      resetEnable: false
   sequence:
    available: true
    sequenceConfigs:
    -
     id: PlatDeptSequence
     type: PlatDeptCodeSequence
     args: {id: 'IB', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: PlatEmployeeSequence
     type: PlatEmployeeCodeSequence
     args: {id: 'IA', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: PlatPowerSequence
     type: PlatPowerCodeSequence
     args: {id: 'IH', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: MerchantPowerSequence
     type: MerchantPowerCodeSequence
     args: {id: 'IL', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: MerchantDeptSequence
     type: MerchantDeptCodeSequence
     args: {id: 'IE', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: MerchantEmployeeSequence
     type: MerchantEmployeeCodeSequence
     args: {id: 'ID', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: MerchantTenantSequence
     type: MerchantTenantCodeSequence
     args: {id: 'IC', maxSequenceValue: '99999999', length: '8', step: '5'}
    -
     id: random
     type: randomSequence
     args: {length: '6'}
    -
     id: ProductRandom
     type: ProductRandomSequence
     args: {length: '10'}
    
  