server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 4048576
spring:
  aop:
    proxy-target-class: true
  zipkin:
    enabled: true
    base-url: http://localhost:7777/
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  rabbitmq: 
    host: 120.78.162.226
    port: 5672
    username: admin
    password: 123456
feign:
  httpclient: 
    enabled: true #feign原生是调用java.url 去发起HTTP请求，此配置是将请求客户端更换成apahce http
  hystrix: 
    enabled: false #关闭熔断
    

azz-merchant-management-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0
azz-client-management-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0
azz-user-service: 
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: false
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
# shiro登录失效时间      
shiro:
  session:
    timeout: 1800000

